### ISSUE TITLE
Use version from Cargot.toml for user agent

### ISSUE THREAD

**Issue by madeindjs** [madeindjs/spider#11]
I think that `user_agent` in `src/configuration.rs` can use crate version from `cargo.toml` file. Maybe it is possible to use something like that :

~~~rs
const VERSION: &'static str = env!("CARGO_PKG_VERSION");
~~~

**Comment by j-mendez** [comment]
This was added in v1.5.0. Closing https://github.com/madeindjs/spider/blob/master/spider/src/configuration.rs#L31.
