### ISSUE TITLE
Concurrency configuration not available in latest release 1.2.1

### ISSUE THREAD

**Issue by digitalsanctum** [madeindjs/spider#12]
README.md suggests there's a `concurrency` configuration option available but is not available in 1.2.1. It's also not listed in docs: https://docs.rs/spider/1.2.1/spider/configuration/struct.Configuration.html

**Comment by madeindjs** [comment]
I don't know why this is not documented but [this option exists](https://github.com/madeindjs/spider/blob/99604f0be22de5436c0bee9574cfe6a05de58713/src/configuration.rs#L22). I also [add a Cargo example](https://github.com/madeindjs/spider/commit/1c7e5c68e209479138340ba69816a7ceb69b4387#diff-8b02272b9bcbb96e8d772106838117ab7fb3cea48c9a90ed450614038be6e7eb) to tests it and it works. So I think this is only a documentation issue.

**Comment by madeindjs** [comment]
It was a documentation issue due to https://doc.rs who not build documentation. I published a new version and It works this time: https://docs.rs/spider/1.2.1/spider/configuration/index.html
