### ISSUE TITLE
spider_cli doesn't install using cargo

### ISSUE THREAD

**Issue by quietlychris** [madeindjs/spider#28]
Hello,

Per the README, I've tried installing `spider_cli` on two different machines, using `$ cargo install spider_cli`. Each time, I receive an error 
```sh
error: could not find `spider_cli` in registry `crates-io` with version `*`
```
Similarly, while other command-line programs distributed in this manner (like `lychee`) have listings on `crates.io` for both `lychee` and `lychee-lib`, I can not find a corresponding `spider_cli` crate available. This may indicate that publishing was not actually successful. 

I have tested on `rustc/cargo 1.60.0` for both `stable` and `nightly`, and actively develop other projects in Rust, so I don't think ti's because of anything exotic or uncommon about my machines' setup.

**Comment by j-mendez** [comment]
@quietlychris hi, thank you for posting this issue. We actually have not published the crate yet for the cli. If you clone the repo and re-run the commands you can get the cli in the mean time. We should have this released soon!

**Comment by quietlychris** [comment]
Sounds great, I'm looking forward to it! Thanks for putting in the time on this, I'm really excited to have a library like this available.

**Comment by j-mendez** [comment]
@quietlychris You can now install the cli via `cargo install spider_cli ` https://crates.io/crates/spider_cli. Thank you!
