### ISSUE TITLE
Add --help option to spider_cli

### ISSUE THREAD

**Issue by quietlychris** [madeindjs/spider#33]
Upon installing `spider_cli`, I pretty immediately tried to check usage information using `spider --help`, which then leads to an immediate panic. I also typed `man spider` (in some ways, I wish the command was actually `spider man`, because that would be delightful). Anyway, of course no man page exists (mostly not for CLI tools installed through `cargo`), so I ended up checking usage on `crates.io`. 

I'd like to recommend adding in a `-help` option to the CLI, because it's a pretty standard feature, and makes using the tool easier on a day-to-day basis, especially for potentially more complicated configuration settings. To that end, it might be worth adding [`clap`](https://crates.io/crates/clap) as a `spider_cli` dependency--in my experience, it makes building fully-featured CLI tools much easier and easy to update as the main repository evolves, and is a commonly-used library in the Rust ecosystem. If you're interested in this, I'd be happy to put together a draft pull request with those changes.

**Comment by j-mendez** [comment]
@quietlychris I agree it would be nice to use clap. We added a simple method for the scan endpoint as a CLI entry since we had issues with clap installs a while back when the projects were not split into a workspace. It should work now in the `spider_cli` file. Would love to see this change.

**Comment by madeindjs** [comment]
Good idea. You can try to implement it if you want to.

Is an external librairy needed or can we simply use `options.contains_key("help")` ?

**Comment by j-mendez** [comment]
@madeindjs @quietlychris added `--help` in https://github.com/madeindjs/spider/pull/34. ` @quietlychris if you want to take a look at adding `spider man` feel free to get your 🕷 on. Good idea since a lot of purposeful information could help to be documented.

**Comment by j-mendez** [comment]
Re opened the issue since, theres an issue with one of the deps in `spider` and the `clap` crate with quotes v1.0. Our release is stalled on our CLI until this is fixed. Right now theres nothing coming up on the next release for the CLI or else I would revert the changes. It should be something simple. Will take a look later. @quietlychris  

![Screen Shot 2022-04-17 at 5 48 37 PM](https://user-images.githubusercontent.com/8095978/163733251-117f4e22-c782-4ef3-8d4c-3336b51c7e77.png)
3

**Comment by j-mendez** [comment]
fixed and published in v.1.5.2 for `spider_cli`.
